### ISSUE TITLE
Embed in Wordpress

### ISSUE THREAD

**Issue by margitZ** [isf-hack-night/reps-app#19]
Put javascript onto website!

**Comment by RS-Crawford** [comment]
Okay, I solved this in a way.

Here's what I found:
- Based on [this answer](https://wordpress.stackexchange.com/questions/67802/most-efficient-way-to-add-javascript-file-to-specific-post-and-or-pages) and [this post](https://ithemes.com/2015/02/17/adding-scripts-wordpress-right-way/) it seems that creating php function using `wp_enqueue_scripts`in `functions.php` is the way to go
- So, I've altered our `functions.php` in the dashboard by adding this function:
```
function load_scripts() {
    global $post;
  
  	if( is_page() || is_single() )
    {
        switch($post->post_name) // post_name is the post slug which is more consistent for matching to here
        {
            case 'test':
                wp_enqueue_script('google_maps', 'https://maps.googleapis.com/maps/api/js?key=[API_KEY]&libraries=places', array(), '', false);
          		wp_enqueue_script('mapbox', 'https://api.mapbox.com/mapbox.js/v3.1.1/mapbox.js', array(), '', false);
	            wp_enqueue_script('reps_app', 'https://ca.state-strong.org/wp-content/uploads/2017/08/bundle.js', array(), '', false);
                break;
        }
    } 
}

add_action('wp_enqueue_scripts', 'load_scripts');
```
- To get to the `functions.php` page in the dashboard:
`Appearance` -> `Editor` then...
![image](https://user-images.githubusercontent.com/12765798/29903511-176ef00e-8db9-11e7-892a-a78d2a563c2e.png)
Click `theme functions` link here
![image](https://user-images.githubusercontent.com/12765798/29903542-3ef854da-8db9-11e7-858b-a5cf502eb1c9.png)

- However, I believe this leaves 2 issues:
  1) It doesn't include the `mapbox.css` file. I wonder if we can just C&P it into the `bundle.js`?
  2) WooThemes discourages using `functions.php` directly in the editor in favor of directly using FTP

- I tried to FTP into our server after getting [Cyberduck](https://cyberduck.io/) and following [these guidelines](https://www.podfeet.com/blog/tutorials-5/ftp-to-wordpress-using-cyberduck/) but I couldn't get it to work

- Currently, the `mapbox.css` is here:
`Tools` -> `Scripts N Styles`
![image](https://user-images.githubusercontent.com/12765798/29903907-2a4c12cc-8dbb-11e7-8de7-b7fabf6bd4d0.png)
Scroll down to here:
![image](https://user-images.githubusercontent.com/12765798/29903983-7f708328-8dbb-11e7-8a68-9ea0842d7074.png)

**Comment by margitZ** [comment]
Awesome!  I remember Wayne saying somethign during a previous hacknight about why FTP wasn't working, but can't remember the details

**Comment by RS-Crawford** [comment]
Right, I'll take that discussion to Slack.

In other news, I added the`mapbox.css` to my local file and was able to debug the issues it was causing (mostly pathing issues for `.png` and `.svg` files, but one lint issue throwing an error), so that problem is solved now.

If we can get the FTP access, we can just transplant the PHP function, but I'm not sure it's 100% necessary.

Given that I'm going to close this.

**Comment by margitZ** [comment]
note to self - remember to update wp bundle.js folder path when uploading a new file for September
