### ISSUE TITLE
Design: Multiple Address boxes

### ISSUE THREAD

**Issue by margitZ** [isf-hack-night/reps-app#5]
"There are two address boxes currently
The one on the top left of the map for change address should only appear after you enter your address"

@RS-Crawford - fixed during meeting?

**Comment by RS-Crawford** [comment]
Yes, I fixed the double up.

However, let's let's have this issue up for now to remind me to switch the sizing of the map header address bar

**Comment by RS-Crawford** [comment]
`MapHeader` now at 100% width in all cases.
